"""SQL migration generation from diff results.

Generates SQL that transforms the *left* database into the *right* database.
Uses temporary-table rebuild for schema-changed tables, guards
``PRAGMA foreign_keys``, and drops/recreates affected triggers around
migration DML.

Two entry points:

* :func:`write_export` — streaming, writes one statement at a time to any
  file-like object.
* :func:`export_as_sql` — convenience wrapper that returns the full SQL as
  a string.
"""

from __future__ import annotations

import io
from typing import TYPE_CHECKING, Any

from patchworks.db.inspector import _open_readonly, _qi, for_each_row, inspect_table
from patchworks.db.types import (
    DatabaseDiff,
    SchemaDiff,
    TableDataDiff,
    TableInfo,
    TableSchemaDiff,
    TriggerInfo,
)

if TYPE_CHECKING:
    from collections.abc import Iterator
    from pathlib import Path


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_export(
    diff: DatabaseDiff,
    out: io.TextIOBase | io.StringIO,  # type: ignore[type-arg]
    *,
    right_path: str | Path | None = None,
) -> None:
    """Write the SQL migration for *diff* one statement at a time to *out*.

    If *right_path* is provided it is opened read-only to stream row data
    for newly added tables via :func:`for_each_row`.  When omitted, the
    path stored in ``diff.right_path`` is used.
    """
    rp = str(right_path) if right_path is not None else diff.right_path
    _write_statements(_generate_statements(diff, rp), out)


def export_as_sql(
    diff: DatabaseDiff,
    *,
    right_path: str | Path | None = None,
) -> str:
    """Return the full SQL migration as a string.

    Suitable for preview; prefer :func:`write_export` for large migrations.
    """
    buf = io.StringIO()
    write_export(diff, buf, right_path=right_path)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Statement generator
# ---------------------------------------------------------------------------


def _generate_statements(
    diff: DatabaseDiff,
    right_path: str,
) -> Iterator[str]:
    """Yield individual SQL statements for the migration."""
    sd = diff.schema_diff

    # Collect all triggers that need to be dropped before DML.
    triggers_to_drop = _triggers_to_drop(sd)
    triggers_to_create = _triggers_to_create(sd, right_path)

    # -- Preamble -----------------------------------------------------------
    yield "-- Migration generated by patchworks"
    yield "PRAGMA foreign_keys = OFF;"
    yield "BEGIN TRANSACTION;"
    yield ""

    # -- Drop affected triggers before DML ----------------------------------
    for tname in sorted(triggers_to_drop):
        yield f"DROP TRIGGER IF EXISTS {_qi(tname)};"

    # -- Removed views ------------------------------------------------------
    for v in sd.views_removed:
        yield f"DROP VIEW IF EXISTS {_qi(v.name)};"

    # -- Modified views -----------------------------------------------------
    for vm in sd.views_modified:
        yield f"DROP VIEW IF EXISTS {_qi(vm.name)};"
        if vm.new_sql is not None:
            yield f"{vm.new_sql};"

    # -- Added views --------------------------------------------------------
    for v in sd.views_added:
        yield f"{v.sql};"

    # -- Removed indexes (standalone, not table-associated) -----------------
    for idx in sd.indexes_removed:
        if idx.sql is not None:
            yield f"DROP INDEX IF EXISTS {_qi(idx.name)};"

    # -- Modified indexes ---------------------------------------------------
    for im in sd.indexes_modified:
        yield f"DROP INDEX IF EXISTS {_qi(im.name)};"
        if im.new_sql is not None:
            yield f"{im.new_sql};"

    # -- Removed tables -----------------------------------------------------
    for t in sd.tables_removed:
        yield f"DROP TABLE IF EXISTS {_qi(t.name)};"

    # -- Added tables (schema + data) ---------------------------------------
    for t in sd.tables_added:
        yield f"{t.sql};"
        # Seed data from the right database.
        yield from _seed_table_rows(t, right_path)

    # -- Modified tables (temporary-table rebuild) --------------------------
    for tm in sd.tables_modified:
        yield from _rebuild_table(tm, right_path)

    # -- Row-level changes for common, schema-identical tables --------------
    modified_table_names = {tm.table_name for tm in sd.tables_modified}
    added_table_names = {t.name for t in sd.tables_added}
    for td in diff.table_data_diffs:
        if td.table_name in modified_table_names:
            continue
        if td.table_name in added_table_names:
            continue
        yield from _row_level_dml(td)

    # -- Added indexes ------------------------------------------------------
    for idx in sd.indexes_added:
        if idx.sql is not None:
            yield f"{idx.sql};"

    # -- Recreate triggers --------------------------------------------------
    for _tname, sql in sorted(triggers_to_create.items()):
        yield f"{sql};"

    # -- Removed triggers (not being recreated) ---
    for tr in sd.triggers_removed:
        if tr.name not in triggers_to_drop:
            yield f"DROP TRIGGER IF EXISTS {_qi(tr.name)};"

    # -- Added triggers (not in recreate set) ------
    for tr in sd.triggers_added:
        if tr.name not in triggers_to_create:
            yield f"{tr.sql};"

    # -- Epilogue -----------------------------------------------------------
    yield ""
    yield "COMMIT;"
    yield "PRAGMA foreign_keys = ON;"


# ---------------------------------------------------------------------------
# Trigger helpers
# ---------------------------------------------------------------------------


def _triggers_to_drop(sd: SchemaDiff) -> set[str]:
    """Triggers that must be dropped before DML."""
    names: set[str] = set()

    # Triggers on tables being removed.
    removed_tables = {t.name for t in sd.tables_removed}
    for tr_tuple in (sd.triggers_removed, sd.triggers_added):
        for tr in tr_tuple:
            if isinstance(tr, TriggerInfo) and tr.table_name in removed_tables:
                names.add(tr.name)

    # Triggers on tables being modified (rebuilt).
    # We need to look at all triggers on modified tables.  We'll collect
    # them from the left database (they'll be dropped before rebuild).
    for tr in sd.triggers_removed:
        names.add(tr.name)
    for tm in sd.triggers_modified:
        names.add(tm.name)

    # Also drop triggers that are being modified.
    return names


def _triggers_to_create(
    sd: SchemaDiff,
    right_path: str,
) -> dict[str, str]:
    """Triggers that must be recreated after DML.

    Returns a mapping of trigger name → CREATE TRIGGER SQL.
    """
    result: dict[str, str] = {}

    # Modified triggers get the new SQL.
    for tm in sd.triggers_modified:
        if tm.new_sql is not None:
            result[tm.name] = tm.new_sql

    # Triggers on rebuilt tables that still exist in the right database.
    modified_tables = {tmsd.table_name for tmsd in sd.tables_modified}
    if modified_tables:
        conn = _open_readonly(right_path)
        try:
            for row in conn.execute(
                "SELECT name, sql FROM sqlite_master WHERE type='trigger'"
            ).fetchall():
                tname: str = row[0]
                tsql: str | None = row[1]
                # Check if this trigger's table was rebuilt.
                tbl_row = conn.execute(
                    "SELECT tbl_name FROM sqlite_master "
                    "WHERE type='trigger' AND name=?",
                    (tname,),
                ).fetchone()
                if tbl_row and tbl_row[0] in modified_tables and tsql:
                    result[tname] = tsql
        finally:
            conn.close()

    return result


# ---------------------------------------------------------------------------
# Table rebuild (temporary-table strategy)
# ---------------------------------------------------------------------------


def _rebuild_table(tm: TableSchemaDiff, right_path: str) -> Iterator[str]:
    """Yield SQL for a temporary-table rebuild of a schema-changed table.

    Strategy:
    1. Rename the existing table to a temp name.
    2. Create the new table with the right-side schema.
    3. Copy compatible data from the temp table.
    4. Drop the temp table.
    5. Recreate indexes on the new table.
    """
    table = tm.table_name
    tmp_name = f"_patchworks_old_{table}"

    yield f"ALTER TABLE {_qi(table)} RENAME TO {_qi(tmp_name)};"

    if tm.new_sql is not None:
        yield f"{tm.new_sql};"
    else:
        return

    # Determine which columns are common to both schemas for data copy.
    conn = _open_readonly(right_path)
    try:
        right_table = inspect_table(conn, table)
        right_col_names = [c.name for c in right_table.columns]
    finally:
        conn.close()

    # Columns in the new schema that were *not* just added (i.e. they
    # exist in the old schema too) are the ones we can copy data for.
    added = {c.name for c in tm.columns_added}
    common = [c for c in right_col_names if c not in added]

    if common:
        cols = ", ".join(_qi(c) for c in common)
        yield f"INSERT INTO {_qi(table)} ({cols}) SELECT {cols} FROM {_qi(tmp_name)};"

    yield f"DROP TABLE {_qi(tmp_name)};"

    # Recreate indexes from the right database.
    conn = _open_readonly(right_path)
    try:
        for row in conn.execute(
            "SELECT sql FROM sqlite_master "
            "WHERE type='index' AND tbl_name=? AND sql IS NOT NULL",
            (table,),
        ).fetchall():
            idx_sql: str = row[0]
            yield f"{idx_sql};"
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Row seeding for new tables
# ---------------------------------------------------------------------------


def _seed_table_rows(table: TableInfo, right_path: str) -> Iterator[str]:
    """Yield INSERT statements for all rows in a newly added table.

    Uses :func:`for_each_row` for bounded-memory streaming.
    """
    conn = _open_readonly(right_path)
    try:
        rt = inspect_table(conn, table.name)
        col_names = [c.name for c in rt.columns]
        if not col_names:
            return

        cols_clause = ", ".join(_qi(c) for c in col_names)

        for row in for_each_row(
            conn,
            table.name,
            pk_columns=rt.primary_key_columns,
            without_rowid=rt.without_rowid,
        ):
            values = [row[c] for c in col_names]
            vals_clause = ", ".join(_sql_literal(v) for v in values)
            yield (
                f"INSERT INTO {_qi(table.name)} ({cols_clause}) VALUES ({vals_clause});"
            )
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Row-level DML for unchanged-schema tables
# ---------------------------------------------------------------------------


def _row_level_dml(td: TableDataDiff) -> Iterator[str]:
    """Yield INSERT/UPDATE/DELETE for row-level changes."""
    table = td.table_name
    key_cols = td.key_columns

    for rd in td.row_diffs:
        if rd.kind == "added" and rd.new_values is not None:
            cols = list(rd.new_values.keys())
            cols_clause = ", ".join(_qi(c) for c in cols)
            vals_clause = ", ".join(_sql_literal(rd.new_values[c]) for c in cols)
            yield (f"INSERT INTO {_qi(table)} ({cols_clause}) VALUES ({vals_clause});")

        elif rd.kind == "removed":
            where = _where_clause(key_cols, rd.key)
            yield f"DELETE FROM {_qi(table)} WHERE {where};"

        elif rd.kind == "modified" and rd.cell_changes:
            sets = ", ".join(
                f"{_qi(cc.column)} = {_sql_literal(cc.new_value)}"
                for cc in rd.cell_changes
            )
            where = _where_clause(key_cols, rd.key)
            yield f"UPDATE {_qi(table)} SET {sets} WHERE {where};"


# ---------------------------------------------------------------------------
# SQL literal helpers
# ---------------------------------------------------------------------------


def _sql_literal(value: Any) -> str:
    """Convert a Python value to a SQL literal string."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, bytes):
        return "X'" + value.hex().upper() + "'"
    # String — escape single quotes.
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _where_clause(key_cols: tuple[str, ...], key_values: tuple[Any, ...]) -> str:
    """Build a WHERE clause matching *key_cols* to *key_values*."""
    parts: list[str] = []
    for col, val in zip(key_cols, key_values, strict=False):
        if val is None:
            parts.append(f"{_qi(col)} IS NULL")
        else:
            parts.append(f"{_qi(col)} = {_sql_literal(val)}")
    return " AND ".join(parts)


# ---------------------------------------------------------------------------
# Statement writer
# ---------------------------------------------------------------------------


def _write_statements(
    stmts: Iterator[str],
    out: io.TextIOBase | io.StringIO,  # type: ignore[type-arg]
) -> None:
    """Write each statement followed by a newline."""
    for stmt in stmts:
        out.write(stmt)  # type: ignore[arg-type]
        out.write("\n")  # type: ignore[arg-type]
